POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "5th blog",
  "author": "Bloggy McBloggerson",
  "url": "www.google.com/blog/bloggy",
  "likes": 22,
  "userId": "624480e38ef4027cd3463c1a"
}