POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "erikSand",
  "name": "Erik Sandstrom"
}
##### other user
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "user",
  "name": "Test User"
}
##### disabled user
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "disabled",
  "name": "Disabled User"
}