PUT http://localhost:3001/api/users/disabled
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVyaWtTYW5kIiwiaWQiOjEsImlhdCI6MTY1NDE4NDQzN30.Ex2Z4yNnWGrF54a41rsiEcQIOrPR04QFvFSNPoX3XTM

{
  "disabled": false
}
##### Non-admin
PUT http://localhost:3001/api/users/disabled
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6MiwiaWF0IjoxNjU0MTg0NTIzfQ.E17wuJCIcUIWFZEkCYLbf3TBndMb4IcQsxu5gk5iK4Q


{
  "disabled": false
}